# <font face="times"><font size="6pt"><p style = 'text-align: center;'> BRYN MAWR COLLEGE

<font size="6pt"><p style = 'text-align: center;'><b><font face="times">Computational Methods in the Physical Sciences</b><br/><br/>

<p style = 'text-align: center;'><b><font face="times">Module 1:  A Brief Introduction to Python and Programming</b><br/><br/>

<p style = 'text-align: center;'><b><font face="times">Part 2 -- Functions, Packages and Plotting</b><br/><br/>

<p style = 'text-align: center;'><font face="times"><font size="3pt"> Adapted from *A Crash Course in Python for Scientists*, version 0.6 <br/>
[Rick Muller](http://www.cs.sandia.gov/~rmuller/), Sandia National Laboratories </p>

 ***Prerequisite modules***: Module 0 

***Estimated completion time***: 3-5 hours  

***Learning objectives***: Become familiar with, and gain practice in using, basic Python constructs

   <img src=" https://imgs.xkcd.com/comics/error_types.png" width="350" height="350"/>
<p style = 'text-align: center;'>Image credit: https://xkcd.com/2303/<br/><br/>


# Outline

## Part 1 - Basics

* [I. Python Overview](Computational_Module-01A-PythonIntro.ipynb#I.-Python-Overview) 
   * [Debugging](Computational_Module-01A-PythonIntro.ipynb#Debugging)
   * [Python as a Calculator](Computational_Module-01A-PythonIntro.ipynb#Using-Python-as-a-Calculator)
   * [Defining Variables](Computational_Module-01A-PythonIntro.ipynb#Defining-Variables)
   * [Strings and Printing](Computational_Module-01A-PythonIntro.ipynb#Strings-and-Printing)
   * [User Input](Computational_Module-01A-PythonIntro.ipynb#User-Input)
   * [Lists](Computational_Module-01A-PythonIntro.ipynb#Lists)
   * [Loops and Iteration](Computational_Module-01A-PythonIntro.ipynb#Loops-and-Iteration)
   * [Slicing](Computational_Module-01A-PythonIntro.ipynb#Slicing)
   * [Booleans](Computational_Module-01A-PythonIntro.ipynb#Booleans-and-Truth-Testing)


## Part 2 - Functions, Packages, Data Input/Output, and Plotting

* [II. Functions](#II.-Functions)  
   * [Function Packages](#Function-Packages)
   * [User-Defined Functions](#User-Defined-Functions)
   * [Function of a Function](#Function-of-a-Function)
   

* [III. Numpy and Scipy](#III.-Numpy-and-Scipy)
   * [Making vectors and matrices, 1-D and 2-D arrays](#Making-vectors-and-matrices,-1-D-and-2-D-arrays)
   * [Slicing Arrays](#Slicing-Arrays)
   * [linspace and arange](#linspace-and-arange)
   * [Array Operations](#Array-Operations)
   * [Optional Arguments](#Optional-Arguments)
   

* [IV. Data Input/Output](#IV.-Data-Input/Output)


* [V. Plotting with Matplotlib](#V.-Plotting-with-Matplotlib) 


## Part 3 - Algorithm Design

* [VI. List Manipulation](Computational_Module-01C-PythonIntro.ipynb#VI.-List-Manipulation)
   * [Searching a List](Computational_Module-01C-PythonIntro.ipynb#Searching-a-List) 
   * [Sorting a List](Computational_Module-01C-PythonIntro.ipynb#Sorting-a-List)
   
   
* [VII. Recursion](Computational_Module-01C-PythonIntro.ipynb#VII.-Recursion)

   
* [VIII. References](Computational_Module-01C-PythonIntro.ipynb#VIII.-References) 

- - -

## II. Functions

### <font color="blue">**Function Packages**</font>

Python's power can be extended greatly through the use of collections of supplementary functions contained in **packages** (referred to as **libraries** in other programming languages).  To keep things simple, most of these package functions are not accessible from a normal Python interactive session.  Instead, you have to **`import`** the package name or individual function. For example, there is a `math` package containing many useful functions. To access, say, the square root function, you can first import the specific function of interest, using the syntax

```python
from math import sqrt
```

and then Python will recognize that function name, e.g.,

In [1]:
from math import sqrt
sqrt(81.3)

9.016651263079881

Alternatively, you can simply import the entire `math` package, but then you should specify a function in the package like this:

In [2]:
import math
math.sqrt(81.3)

9.016651263079881

If a package has been imported using this method, then typing
```python
dir(package name)
```
will produce a list of the functions in the package:

In [3]:
dir(math)

['__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'pi',
 'pow',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc']

So we see that `math` has a built-in value for $\pi$, which we call as shown:

In [4]:
print("Pi = %.18f" % math.pi)

Pi = 3.141592653589793116


You also can import an entire package using this syntax (where `*` is a **wildcard** that stands for "everything"):

In [5]:
from math import *

***Note***: Usually, it's safe to import the entire package, but if your code might require a lot of computer memory (RAM) in order to run, or if memory capacity is a concern for any other reason, it would be better to import only the specific functions you need from a package, rather than the entire package. 

***Caution***:  Some packages occasionally include functions with the same name; e.g., both the `math` and the `numpy` packages contain the trig functions `sin()`, `cos()`, and `tan()`, as well as other functions in common.  If you import both packages using `from [package] import *`, how do you know which function you're getting when you call one with a shared name?  

The most common way to deal with potential name conflict issues is to import packages using the first method, `import [package]`, and then a function can be referenced as `package.function`; e.g. `math.sqrt`.   

To save typing, you can import packages with "nicknames"; e.g., 

In [6]:
import numpy as np

Now you can specify the particular version of the function you want using the syntax `nickname.function`:

In [7]:
print("Pi = %.18f" % np.pi)

Pi = 3.141592653589793116


The approach of importing an entire library is used in this notebook.  In other modules or notebooks that require only a small number of imported functions, those functions may be imported individually as needed.

***Note:***  Since `numpy` contains all of the functions that `math` contains, plus others, and since it permits array operations in addition, there's no need to import the `math` package if you're also importing `numpy`.

<a href='#Outline'>Back to the Top</a>

### <font color="blue">**User-Defined Functions**</font>

Python allows you to define your own mathematical functions, which provides lots of flexibility and enables you to "package" code in a way that makes it easy to use wherever you need.  This can greatly improve the efficiency of your coding.  

We define a function with the **`def`** statement in Python:

In [8]:
def poly1(x):
    '''Returns a polynomial of the input value x'''
    return 3.5 * x**2 - 2 * x + 1

Note that the function itself is defined as a code block (a colon followed by an indented block), like in an `if` statement.  Also note that the first line of the function is a single string (which is optional, but highly recommended), surrounded front and back by three single quotes. This is called a **docstring**, and is a special kind of comment that often is available to people using the function through the Python command line.

If you define a docstring for each of your functions, it makes it easier for other people to use them, since you can provide instructions on the **arguments** (inputs) and **return values** (outputs) of the function which users can obtain using the `help` command.  For example:

In [9]:
help(poly1)

Help on function poly1 in module __main__:

poly1(x)
    Returns a polynomial of the input value x



Also note the `return` statement at the end of the function definition.  This allows `poly1` to produce an output which can be used by other code; in this case, the output is the value of the calculation following `return` for a given value of `x`.  What follows the `return` statement can be a single variable, multiple comma-separated variables, or a calculation.

Just as importing two packages with a shared function name leads to uncertainty about what behavior you might get when calling that function, the same thing will happen if you define a function with the same name as a package function, so that risk should be avoided by defining functions with names that are not likely to be the same as ones that already exist.

In a situation when the expression we wish to return is complicated, it makes for clearer code to break it up into separate terms, e.g.,

In [10]:
def poly1(x):
    '''Return a polynomial of the input value x'''
    
    term1 = 3.5 * x**2
    term2 = 2 * x
    term3 = 1
    
    return term1 - term2 + term3

To run a function we "call" it with appropriate inputs:

In [11]:
poly1(2)

11.0

The output of the function in this case was printed to the screen, but it has not been stored.  To store the output for future use, the function is called as shown here (for one output):

In [12]:
x = poly1(-17.9)

print(x)
print(x*x)

1158.235
1341508.3152249998


The second printed value proves that the output of `poly1` actually has been stored in `x`.

Note that Python functions can have multiple inputs and outputs.  For example, we could define a function  

```python
def myfun(x, y, z):
    [code]
    return a, b```
        
Here, `x`, `y`, etc. are arguments (the inputs) to the function, and `a` and `b` are the return values.  (You can have no return values -- e.g. if the function just prints or plots its output -- or one return value, two return values,... however many you want.)  You would call this function as

```python
out1, out2 = myfun(xval,yval)```

Here, `out1` and `out2` capture the values of `a` and `b` outputted by the `return` statement.

For example:

In [13]:
def square_cube(x):
    '''Return the square and cube of the input value x'''
    
    a = x*x
    b = x**3
    return a, b

In [14]:
out1, out2 = square_cube(7)
print(out1, out2)

49 343


So, this function outputs both the square and cube of the input, `7`, and the returned values `out1` and `out2` now can be used in other operations:

In [15]:
out1 + out2

392

As another example of a function, here's one that will find and print all of the elements of a list of numbers that are smaller than a specified value, and print their indices.  

In [16]:
def findbelow(mylist, val):
    '''Find and print all of the elements (and their indices) in mylist smaller than val.'''
    
    num = len(mylist)  # gets length of input list
    
    for i in range(num):
        if mylist[i] < val:
            print('%g, at index %d, is less than %g' %(mylist[i], i, val))

In [17]:
findbelow([8, -3.2, 4, 16.3, -5], 5)

-3.2, at index 1, is less than 5
4, at index 2, is less than 5
-5, at index 4, is less than 5


(Remember that Python list indexes start at 0.)

<a href='#Outline'>Back to the Top</a>

### <font color="blue">**Function of a Function**</font>

Another great feature of Python functions is that you can pass one function as an argument to another, as long as the second function is designed to take a function as an argument.  For example, let's define a function as follows

In [18]:
def square(x):
    return x*x

and another function that takes a function as input:

In [19]:
def sumfunc(func, a, b):
    return func(a) + func(b)

This function calls another function `func`, applies it to the inputs `a` and `b`, and sums the results.  

<font color="green"><b>Breakpoint 3</b></font>: Predict the output of the function call `sumfunc(square,2,3)`.  Then, check your prediction by entering and running this function call in the following code cell.  (Make sure to run the two code cells above.)

Note that we don't have to pass an argument (`x`) along with the function name `square` when we pass it to the second function (`sumfun`).  We simply pass the function name itself.  (However, whatever we do with `square` inside `sumfun` has to respect the arguments that `square` is designed to take.)  

This ability of a function to act on another function just by name is particular to (some) modern programming languages.  This capability does not exist in older languages like FORTRAN and C.

 The input `x` in the function definition of `square`, or the inputs `a` and `b` to `sumfun`, could be entire *arrays* of values; the functions would output corresponding arrays consisting of the values of the functions applied to each of the array elements.  In order to do this, the input arrays must be created as `numpy` arrays.  For example:

In [20]:
inarray1 = np.array([1, 3, 5])
inarray2 = np.array([2, 4, 6])
print(square(inarray1))
print(square(inarray2))

[ 1  9 25]
[ 4 16 36]


In [21]:
sumfunc(square, inarray1, inarray2)

array([ 5, 25, 61])

Here, `sumfun` has computed the array [$1^2 + 2^2$, $3^2 + 4^2$, $5^2 + 6^2$].

**Exercise \#8**

Write a function to output the value of the Gaussian function $f(x;m,\sigma) = \dfrac{1}{\sqrt{2 \pi} \sigma} \exp \left[ -\dfrac{1}{2} \left(\dfrac{x-m}{\sigma}\right)^2 \right]$, where $m$, $\sigma$, and $x$ are inputs to the function.  (We're thinking of $x$ as a variable and $m$ and $\sigma$ as parameters.)  Evaluate the function for $m = 0$, $\sigma = 2$, $x = 1$.  

*Notes*: (i) the $\sigma$ in the first factor is not inside the square root; (ii) "$\exp(x)$" means $e^x$.

<a href='#Outline'>Back to the Top</a>

- - - - -

## III. Numpy and Scipy

The power of Python is greatly enhanced by a number of large [packages](#Function-Packages), as mentioned in Module 0 and above.  [Numpy](http://numpy.org) contains core routines for doing fast vector, matrix, and linear algebra-type operations in Python. [Scipy](http://scipy) contains additional routines for optimization, special functions (e.g., Laguerre and Hermite polynomials), and so on. Both contain programs written in C and Fortran so that they're as fast as possible. Together, they give Python roughly the same capability that the [Matlab](http://www.mathworks.com/products/matlab/) program offers. (In fact, if you're an experienced Matlab user, there's a [guide to Numpy for Matlab users](http://www.scipy.org/NumPy_for_Matlab_Users) just for you.)

To add the capabilities of these routines, we have to call them, as shown below.

### <font color="blue">**Making Vectors and Matrices, 1-D and 2-D Arrays**</font>

Fundamental to both `numpy` and `scipy` is the ability to work with vectors and matrices.  (Note that `numpy` has distinct "matrix" objects that differ somewhat from the 2-D arrays that will be discussed below.  See the `numpy` documentation for details.)

As seen above, you can create vectors from lists using the **`array`** command:

In [22]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

You can pass in a second argument to `array` that gives the data type of the values in the array. There are a number of types [listed here](http://docs.scipy.org/doc/numpy/user/basics.types.html) that the values can have. Some of these are represented by (or "aliased to" in Python-speak) single character codes. The most common ones are 'd' (double precision floating point number), 'D' (double precision complex number), and 'i' (int32). Below are examples; note the different forms of the outputs.

In [23]:
np.array([1,2,3,4,5,6],'d')

array([1., 2., 3., 4., 5., 6.])

In [24]:
np.array([1,2,3,4,5,6],'D')

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j])

(Here, '`j`' represents the square root of `-1`, usually denoted as `i` by physicists.)

In [25]:
np.array([1,2,3,4,5,6],'i')

array([1, 2, 3, 4, 5, 6], dtype=int32)

To build 2-D arrays, you can use the `array` command with lists of lists:

In [26]:
np.array([[0,1],[1,0]],'d')

array([[0., 1.],
       [1., 0.]])

You can also form empty (zero) matrices of arbitrary shape (including vectors, which Numpy treats as matrices with one row), using the **`zeros`** command:

In [27]:
np.zeros((3,3),'d')

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

The first argument is a tuple containing the shape of the matrix (enclosed in parentheses), and the second is the data type argument, which uses the same conventions as in the `array` command. Thus, you can make row vectors:

In [28]:
np.zeros((1,3),'d')

array([[0., 0., 0.]])

or column vectors:

In [29]:
np.zeros((3,1),'d')

array([[0.],
       [0.],
       [0.]])

There's also an **`identity`** command that behaves as you'd expect to create the identity matrix (with `1`'s along the diagonal and `0`'s everywhere else):

In [30]:
np.identity(4,'d')

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

as well as a **`ones`** command to produce an array of all `1`'s.

<a href='#Outline'>Back to the Top</a>

### <font color="blue">**Slicing Arrays**</font>

The elements of an array can be accessed using the slicing technique seen for lists:

In [31]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]],'i')
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


<font color="green"><b>Breakpoint 4</b></font>: Predict the result of the command

```python
print(arr[1,2])```

and then test it in the cell below.

Other examples:

In [32]:
print(arr[2,1:])
print(arr[1])
print(arr[1,:])

[8 9]
[4 5 6]
[4 5 6]


Note that the second and third expressions, `arr[1]` and `arr[1,:]`, access all of the elements in the row with index `1`.  In general, the notation `[i,:]` refers to all of the elements in the row with index `i`.

<font color="green"><b>Breakpoint 5</b></font>: in the cell below, enter code to extract the entire last *column* of `arr`, using the "`:`" notation, and execute the cell to test your code.

<a href='#Outline'>Back to the Top</a>

### <font color="blue">**linspace and arange**</font>

The **`linspace`** and **`arange`** commands are the best ways to make a sequence of regularly-spaced values; e.g., as points at which to plot a function.

`linspace` makes a linear array of points *from a specified starting value to a specified ending value*:

In [33]:
np.linspace(0,1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

Note that the upper limit of the specified range is included among the values.

If you provide a third argument, it takes that as the number of points to generate. If you don't provide the argument, it gives an array of length 50.

In [34]:
x = np.linspace(0,1,11)
print(x)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


 As noted, `linspace` is an easy way to make coordinates for plotting. Functions in the `numpy` library can act on an entire array (or even a matrix) of points at once. Thus,

In [35]:
x = np.linspace(0,2*np.pi)

np.sin(x)

array([ 0.00000000e+00,  1.27877162e-01,  2.53654584e-01,  3.75267005e-01,
        4.90717552e-01,  5.98110530e-01,  6.95682551e-01,  7.81831482e-01,
        8.55142763e-01,  9.14412623e-01,  9.58667853e-01,  9.87181783e-01,
        9.99486216e-01,  9.95379113e-01,  9.74927912e-01,  9.38468422e-01,
        8.86599306e-01,  8.20172255e-01,  7.40277997e-01,  6.48228395e-01,
        5.45534901e-01,  4.33883739e-01,  3.15108218e-01,  1.91158629e-01,
        6.40702200e-02, -6.40702200e-02, -1.91158629e-01, -3.15108218e-01,
       -4.33883739e-01, -5.45534901e-01, -6.48228395e-01, -7.40277997e-01,
       -8.20172255e-01, -8.86599306e-01, -9.38468422e-01, -9.74927912e-01,
       -9.95379113e-01, -9.99486216e-01, -9.87181783e-01, -9.58667853e-01,
       -9.14412623e-01, -8.55142763e-01, -7.81831482e-01, -6.95682551e-01,
       -5.98110530e-01, -4.90717552e-01, -3.75267005e-01, -2.53654584e-01,
       -1.27877162e-01, -2.44929360e-16])

A similar function is `arange`, which creates a sequence of values *with a specified interval between them*; e.g.

In [36]:
y = np.arange(1,3,0.2)

print(y)

[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8]


This is like the `range` function, but it can produce noninteger values, and the output is an array rather than a list.  Note that the last value in the specified interval (`3`, in this case) is *not* included in the sequence of values generated.  (If the step size is not specified, it defaults to `1`.)

To recap, `linspace` creates an array with a *specified number of elements*, while `arange` creates an array with a *specified interval between the elements*.

***WARNING:*** when making arrays with very large numbers of elements, `arange` is *much* slower than `linspace`.

**Exercise \#9**

(a) Construct and print out a sequence of 12 values ranging from 1.1 to 1.9 (including both limits).  

(b) Construct and print out a sequence of 12 values starting from 5.0 with an interval of 2.5 between them.

<a href='#Outline'>Back to the Top</a>

### <font color="blue">**Array Operations**</font>

#### *Ignore this section and the Exercise at the end of the section if you haven't yet had a course in linear algebra.*

Array objects act like you would expect them to when multiplied by scalars:

In [37]:
print("The 3 x 3 identity matrix: \n", np.identity(3,'d'), "\n")  # "\n" or '\n' inside a print() does a "carriage return"

print("Multiplied by 0.125:")
print(0.125 * np.identity(3,'d'))

The 3 x 3 identity matrix: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

Multiplied by 0.125:
[[0.125 0.    0.   ]
 [0.    0.125 0.   ]
 [0.    0.    0.125]]


as well as when you add two matrices together. (Of course, the matrices have to be the same shape.)

In [38]:
array1 = np.identity(2,'i')
print("Array #1:\n", array1, "\n")

array2 = np.array([[1,1],[1,2]])
print("Array #2:\n", array2,"\n")

print("These arrays add to give:")
print(array1 + array2)

Array #1:
 [[1 0]
 [0 1]] 

Array #2:
 [[1 1]
 [1 2]] 

These arrays add to give:
[[2 1]
 [1 3]]


(Note how the `\n`, or **newline** character in the `print` statements that display the arrays results in them being formatted nicely.  If you print them without this character, their rows don't align well.)

Something that confuses Matlab users is that the times (*) operator of Python gives element-wise multiplication (e.g., the `1`-`2` element of one array times the `1`-`2` element of the other) rather than matrix multiplication:

In [39]:
arr2 = np.array([[1,2], [3,4]],'d')
print('arr2 is:\n', arr2, '\n') 

id2 = np.identity(2)
print('id2 is:\n', id2, '\n')

print('Their * product is\n', id2 * arr2)

arr2 is:
 [[1. 2.]
 [3. 4.]] 

id2 is:
 [[1. 0.]
 [0. 1.]] 

Their * product is
 [[1. 0.]
 [0. 4.]]


Thus, when operating on arrays `A` and `B`, the **`*`** operator produces the array whose `[i,j]` element is `A[i,j] * B[i,j]`.   

To get the usual matrix multiplication, you need the **`dot`** command:

In [40]:
np.dot(id2, arr2)

array([[1., 2.],
       [3., 4.]])

`dot` can also do dot products of vectors (duh!),

In [41]:
v = np.array([3,4],'d')   # create vector (3, 4)
print("v:", v, "\n")

print("The square root of dot(v,v):", np.sqrt(np.dot(v,v)))      # take square root of the vector dotted with itself

v: [3. 4.] 

The square root of dot(v,v): 5.0


`dot` also does matrix-vector products:

In [42]:
mat = np.array([[1,2],[3,4]],'d')

vec = np.array([[5],[10]],'d')

print("Matrix:\n", mat, '\n')
print("Vector:\n",vec, '\n')

print("Product of matrix with vector:\n", np.dot(mat,vec))

Matrix:
 [[1. 2.]
 [3. 4.]] 

Vector:
 [[ 5.]
 [10.]] 

Product of matrix with vector:
 [[25.]
 [55.]]


There are **`determinant`**, **`inverse`**, and **`transpose`** functions that act as you would expect. Transpose can be abbreviated with ".T" at the end of a matrix object:

In [43]:
m = np.array([[1,2],[3,4]])

print("Original matrix:\n", m, '\n')

print("Transposed matrix:\n", m.T)

Original matrix:
 [[1 2]
 [3 4]] 

Transposed matrix:
 [[1 3]
 [2 4]]


There's also a **`diag()`** function that takes a list or a vector and puts it along the diagonal of a square matrix. 

In [44]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

We'll find this useful later on.

One of the key benefits of using arrays rather than lists (or tuples) is that `numpy`'s functions are designed to work on entire array rows or columns at a time.  For example, if we want to divide a row of a matrix by a constant, this is how it would be done using an array to represent the matrix:

In [45]:
arr3 = np.array([[1,2,3],[4,5,6]],'d')
print("The array:\n", arr3, '\n')

print("The squares of the elements in row 0:\n", arr3[0]**2, '\n')

print("The sines of the array elements:\n", np.sin(arr3))

The array:
 [[1. 2. 3.]
 [4. 5. 6.]] 

The squares of the elements in row 0:
 [1. 4. 9.] 

The sines of the array elements:
 [[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]


Note how, in the second `print` statement, the first row of the array `arr3` was identified simply as `arr3[0]`.

If we try the same approach with a list, we get an "unsupported operand type(s)" error that tells us that the power operator `**` does not work on list elements:

In [46]:
arrlist = [[1,2,3],[4,5,6]]

print("The arrlist object has type", type(arrlist))      # to confirm that arrlist is a list

print(arrlist[0][:]**2)   # square the elements in the first row

The arrlist object has type <class 'list'>


TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

Note that to identify an element in a list of lists, the indices must be entered in *separate* pairs of brackets; e.g., the `i`-`j` element of `mylist` would be `mylist[i][j]`.  The same element would be identified as `myarray[i,j]` in an array.

Interestingly, the following does work with a list:

In [ ]:
np.sin(arrlist)

So, some `numpy` functions work on lists as well as on arrays.

**Exercise \#10**

Compute the value of the vector-matrix product $\mathbf{a} \cdot \mathbf{B} \cdot \mathbf{c}$, where $\mathbf{a} = [1, 2, 3, 4]$, $\mathbf{B}$ is the $4 \times 4$ identity matrix, and $\mathbf{c} = [1, 2, 3, 4]$ as a column vector.  (The vectors should be defined as arrays, not lists, even though you might be able to make it work with lists.)  Your answer should be a single number.

<a href='#Outline'>Back to the Top</a>

### <font color="blue">**Optional Arguments**</font>

So far, we have seen how to define functions that have a fixed number of arguments.  Now we'll learn how to include more general types of arguments.  

As an example, recall that the `linspace` function can take either two arguments (for the starting and ending points):

In [ ]:
np.linspace(0, 1)

or it can take three arguments, for the starting point, the ending point, and the number of points:

In [ ]:
np.linspace(0, 1, 5)

You can also pass in a **keyword** to exclude the endpoint (which changes the other points):

In [ ]:
np.linspace(0, 1,  5, endpoint=False)

One type of additional argument we can provide is indicated in a function definition as **`*args`**.  This allows the user to input any number of arguments, which can be numbers, strings, or lists/arrays.  The individual arguments that make up the set of arguments then are identified in the code as `args[0]`, `args[1]`, etc.  For instance, consider this code (which is not particularly useful!):

In [ ]:
def multiPrint(repeat, *args):
    '''Print the inputs given in *args "repeat" times.'''
    
    numin = len(args)       # the number of unspecified inputs
    print("The number of arguments in *args is", numin, '\n')
    
    for i in range(repeat):      # repeat the printout below
        for j in range(numin):   # print out each element of args
            print(args[j])
    

In [ ]:
multiPrint(3, "Hello", [5.3, 6])

The first argument to `multiPrint` (`3`) is the number of times to print out the other arguments -- the ones contained in `*args` -- of which there are two: the string `"Hello"` and the list `[5.3, 6]`.  

We also can specify a default value for anything that might have a "usual" value.  Here, we do that in a different function:

In [ ]:
def multiHello(repeat=2):
       
    for i in range(repeat):      # repeat the printout below
        print("Hello!")
    

If we just call it without entering an argument, we get the default output:

In [ ]:
multiHello( )

If we want a different value, we just provide it to the function:

In [ ]:
multiHello(3)

Note that we could not do this with the initial argument `repeat` in the `multiPrint` function.  If we defined the function as `def multiprint(repeat=2, *args)` then to get the default number of repetitions (without typing in that number) we would have to call it like this `multiprint( , "Hello", [5.3, 6])`, but Python gives a syntax error because of the "`,`" with nothing in front.  

In [ ]:
def multiPrintTry(repeat=2, *args):
    '''Print the inputs given in *args "repeat" times.'''
    
    numin = len(args)       # the number of unspecified inputs
    print("The number of arguments in *args is", numin, '\n')
    
    for i in range(repeat):      # repeat the printout below
        for j in range(numin):   # print out each element of args
            print(args[j])
    

In [ ]:
multiprint( , "Hello", [5.3, 6])

<a href='#Outline'>Back to the Top</a>

- - -

## IV. Data Input/Output

There are several ways to export and import data within the Python universe.  Among the easier ways are to use `numpy`'s `save`, `savez`, and `savetxt` functions.  The first two functions save a single array and multiple arrays, respectively (in a format not readable by humans) in files with `.npy` and `.npz` extensions, respectively.  The `savetxt` function saves a single array (in a human readable format) with any extension provided by the user.  The cell below shows the syntax to use with these functions in order to save arrays `A` and `B`:

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])


np.save('arrayA', A)                    # saves a single array, A, in file "arrayA.npy"

np.savez('arraysAB', arrA=A, arrB=B)    # saves arrays A & B, with labels "arrA" and "arrB", in file "arraysAB.npz"

np.savetxt('arrayA.dat', A)             # saves array A in file "arrayA.dat"

If you ran the cell above, you should see the three files in the directory where this notebook is located.

The corresponding functions to read in the data are `load` -- for arrays saved using `save` or `savez` -- and `loadtxt` for an array saved using `savetxt`:

In [ ]:
A1 = np.load('arrayA.npy')

AB = np.load('arraysAB.npz')

A2 = np.loadtxt('arrayA.dat')


print("A1 is \n", A1)

print("A2 is \n", A2)

print("The first array in AB is \n", AB['arrA'])

print("The second array in AB is \n", AB['arrB'])

See the documentation on the **Pandas** data analysis library (https://pandas.pydata.org) for more ways to save and import data.

<a href='#Outline'>Back to the Top</a>

- - -

## V. Plotting with Matplotlib

We can generally understand data better by plotting it.  Python has a powerful plotting library called [Matplotlib](http://matplotlib.sf.net) , which provides capabilities very similar to those of Matlab. The IPython notebook interface we are using for these notes has that functionality built in.

As an example, we'll compare two different functions, an exponential function, and the factorial function, both of which grow faster than polynomially. Which one grows the fastest? Let's plot them.  

First, compute the exponentials:

In [ ]:
import math
expon = []
for i in range(21):
    expon.append(math.e ** i)
    
print("The first five values of the exponential function: \n", expon[:5])   # the first five values

Next let's generate the factorials:

In [ ]:
facts = []                         # create list
for i in range(21):
    facts.append(math.factorial(i))     # compute newest value and append to list
    
print("The first five values of the factorial function: \n", facts[:5])   # the first five values

Now we use the Matplotlib function `plot` to compare the two.  To do that, though, we have to set up the notebook to display the plot.  <font color="red">In all notebooks using Matplotlib, the two lines of code below should be included.</font>  The first code line tells the notebook to display the plot right in the notebook, while the second line imports all of the  Matplotlib functions that we usually need.  

In [ ]:
%matplotlib inline
from matplotlib.pyplot import *

***IMPORTANT***: you might occasionally have trouble with plotting in a notebook unless the two lines in the cell above appear in the first code cell of the notebook and it is executed prior to all other code cells.

Matplotlib plots can display axis labels, legends, and a title:

In [ ]:
plot(facts, label="factorial")
plot(expon, label="exponential")
xlabel("n")
ylabel("function values")
title("Factorial and Exponential Functions")
legend()

The factorial function grows much faster. In fact, you can't even see any change in the exponential sequence. It's not entirely surprising: a function where we multiply by the growing integer *n* in each iteration is bound to grow faster than one where we multiply by the constant *e* in each iteration.

***Note***: We have not given the `plot` function a list of $x$ values; in this case, it assumes the $x$ values are 0, 1, 2, ... .  To plot against a different set of values, just provide those to `plot`:

In [ ]:
xvals = range(0, 63, 3)   # every third value

In [ ]:
plot(xvals, facts)
xlabel("n")
ylabel("function values")

Note that the y values have not been recomputed: they've just been plotted against a different set of x values.

Depending on the versions of jupyter and `matplotlib` being run, sometimes, if you hover your cursor over a plot, a "resize" control will appear at the lower right corner that lets you drag the corner to shrink and enlarge the plot.

We can plot different style lines, or show data point markers, or reposition the legend:

In [ ]:
plot(facts,'r-',label="Factorial line")
plot(facts,'bo',label="Factorial points")
xlabel("n")
ylabel("function values")
legend(bbox_to_anchor=(1.5,1))

The color symbols `r`, `b`, `g`, `c`, `y`, `m`, `k`, and `w` represent the colors red, blue, green, cyan, yellow, and magenta, black, and white, respectively.  (Other colors are available -- see the online `Matplotlib` documentation pages.)

The symbol (`o`) creates large dots, a period (`.`) creates small ones; (`-`) creates solid lines, (`--`) creates dashed lines, and (`-.`) creates dash-dot lines.

Besides the `bbox_to_anchor` function, the legend location also can be specified using `loc = N` in the legend command.  `N = 1`, `N = 2`, `N = 3`, and `N = 4` are the upper-right, upper-left, lower-left, and lower-right corners, respectively.  Similarly, `N = 5`, `N = 6`, `N = 8`, and `N = 9` put the legend in the middle of the right, left, bottom, and top sides, respectively. 

In [ ]:
plot(facts,'r-',label="Factorial line")
plot(facts,'bo',label="Factorial points")
xlabel("n")
ylabel("function values")
legend(loc=6)


We can plot the two functions on a semilog plot to see them a little more clearly:

In [ ]:
semilogy(facts,label="factorial")
semilogy(expon,label="exponential")
xlabel("n")
legend(loc=9)

Note that, as you'd expect, the exponential function is linear in a semilog plot.

We can plot the two functions in separate subplots:

In [ ]:
subplots(1,2)
subplot(1,2,1)
semilogy(facts)
xlabel("n")
title('factorial')

subplot(1,2,2)
semilogy(expon,color='g')
xlabel("n")
title('exponential')

To create two (or more) plots in separate graph frames, use the `figure()` command to create a new frame:

In [ ]:
semilogy(facts)
xlabel("n")
title('factorial')

figure()
semilogy(expon,color='g')
xlabel("n")
title('exponential')

**Exercise \#11**

Plot the functions $f_1(n) = n$ and $f_2(n) = n^2$ on the same plot, for integer $n$ in the range $0 \rightarrow 10$. Display a legend in the upper-left corner, label the $x$-axis with n and the $y$-axis with f(n).


The `matplotlib` library also has a way to plot graphs in polar coordinates.  To do this, it appears to be necessary first to create a figure, then to create a set of polar axes as a "subplot" in that figure, as here:

```python
fig = figure()
ax = fig.add_subplot(111, polar=True)
```

The `fig.add_subplot` command can be used to create multiple subplots arranged in an "array."  Note that we give it three digits to specify a subplot.  The first two digits specify the shape of the array of subplots: `11` means a single plot, `12` means a 1x2 row of subplots, `31` means a 3x1 column of subplots, etc.  The third digit specifies where the current subplot is to appear in the array of subplots.  So, if you want two subplots side-by-side, you would denote the first one as something like `ax1 = fig.add_subplot(121, polar=True)` and the second one as `ax2 = fig.add_subplot(122, polar=True)`.  (The names `ax1` and `ax2` are arbitrary.)

The code below creates an example polar plot that happens to depict the curve given by $\theta(r) = 4 \pi r$.

In [ ]:
fig = figure()
ax = fig.add_subplot(121, polar=True)
r = np.arange(0,1,0.001)          # create list of values at increasing radii
theta = 4 * np.pi * r             # the theta values to be plotted corresponding to the list of r values...
                               # ... we could have any function of r here, but this one is particularly simple

line = ax.plot(theta, r, color='orange', lw=3)   # plot theta vs. r on the set of axes in the subplot labeled 'ax'

**Exercise \#12**

Plot two subplots side by side: one duplicating the figure above, and a second showing a blue curve just like the orange one but rotated $90^\textrm{o}$ counterclockwise.

Another type of plot that you might want to create fairly often is a color plot in which the color of each pixel represents the value of some (scalar) parameter at that point (this will work for a grayscale image as well).  For this type of plot, use the **`imshow`** function:

In [ ]:
values = np.zeros([100,100],float)

for i in range(100):
    for j in range(100):
        values[i,j] = i + j    # for something to plot, set each pixel's value to the sum of its row & column indices
        
imshow(values)

There are many color schemes (known as **colormaps**) that you can use in these plots.  It's also worth noting that the function `imshow` can be used to display images stored as arrays.

Yet another type of plot that can be created with `matplotlib` is a 3-D plot.  To do this, we need to import another function using

```python
from mpl_toolkits.mplot3d import Axes3D
```

The following code illustrates a curve in 3-D.  After creating the arrays of ($x$, $y$, $z$) coordinates to be plotted, it creates a new figure and defines its axes as 3-D, using the line `ax = fig.gca(projection = '3d')`.  (`gca` means "get current axes."  This terminology may be familiar from Matlab.)  The `plot` function is called for these axes, and the three sets of coordinates are provided.

In [ ]:
from mpl_toolkits.mplot3d import Axes3D

tvals = np.arange(0.1, 20,0.1)      # times from 0.1 to 10, stepping by 0.1
xvals = np.cos(tvals)/tvals**.25    # makes a nice inward spiral
yvals = np.sin(tvals)/tvals**.25
zvals = tvals

fig = figure()
ax = fig.gca(projection = '3d')
ax.plot(xvals, yvals, zvals)
xlabel('x')
ylabel('y')

Unfortunately, when rendered inside an IPython notebook these images are not manipulable: you can't click-and-drag to rotate them, as you can do in some other interactive environments.  Maybe this capability will be added in the future....

There are many more things you can do with Matplotlib. We'll be looking at some of them in the modules. In the meantime, if you want an idea of the different kinds of graphics you can create, look at the Matplotlib [Gallery](http://matplotlib.org/gallery.html).  Clicking on one of the figures will bring you to a new page, at the top of which you should find the Python source code used to create the figures on the page.  You can download the code, open it in a text editor (it may not be easily readable), and copy-and-paste the text into a notebook cell.  Remember to precede it with another code cell (executed first) containing the lines 

```python
%matplotlib inline
from matplotlib.pyplot import *
```

Rob Johansson's IPython notebook [Introduction to Matplotlib](http://nbviewer.ipython.org/urls/raw.github.com/jrjohansson/scientific-python-lectures/master/Lecture-4-Matplotlib.ipynb) also is good.

<a href='#Part-2'>Back to the Top</a>

### <font color="blue">**Recap**</font>

* Functions that extend the power of Python can be imported from packages.  You can import individual functions from a package (using `from <package> import function1, function2`, etc.) or import the entire package (i.e., `import <package>` or `from <package> import *`).  


* You can define your own Python function using the `def` statement followed by a function name, then a set of parentheses (with any arguments enclosed), and then a colon.  All of the code to be executed by the function must be indented below the `def` line.  Python even lets you pass the name of one function as an argument to another function.  In order for your code to pass  its results in a form usable by other code, end the function with a `return` statement followed by the values or variables to be outputted.


* `numpy` and `scipy` are two of the most important packages for scientists.  They extend Python's numerical computation and symbolic math capabilities, respectively.  


* `numpy` functions enable the creation of arrays and matrices, and the package has built-in functions for creating and performing common operations on those structures.  


* The `matplotlib` package gives Python extensive scientific plotting capabilities, similar to those of Matlab.

### Breakpoint Answers


**Breakpoint 3:** The output is $13$, because `sumfun(square, 2, 3)` calls `square` with the inputs $2$ and $3$, computing $2^2 + 3^2 = 13$.

**Breakpoint 4:** The command prints `6`, because it's the element with row index `1` and column index `2` (the *second* row and *third* column, since the first row and column have index `0`).  
$$ $$
**Breakpoint 5:** One could use the code `arr[:,-1]`, which selects all rows and the last column. 
 
 

<font size="5pt">**End of Part 2**